/* eslint-disable no-undef */
const rowsKeyboard = [
  [
    {
      code: 'Backquote',
      en: '`',
      enShift: '~',
      ru: 'ё',
      ruShift: 'Ё',
      ruCaps: 'Ё',
    },
    {
      code: 'Digit1',
      en: '1',
      enShift: '!',
      ru: '1',
      ruShift: '!',
    },
    {
      code: 'Digit2',
      en: '2',
      enShift: '@',
      ru: '2',
      ruShift: '"',
    },
    {
      code: 'Digit3',
      en: '3',
      enShift: '#',
      ru: '3',
      ruShift: '№',
    },
    {
      code: 'Digit4',
      en: '4',
      enShift: '$',
      ru: '4',
      ruShift: ';',
    },
    {
      code: 'Digit5',
      en: '5',
      enShift: '%',
      ru: '5',
      ruShift: '%',
    },
    {
      code: 'Digit6',
      en: '6',
      enShift: '^',
      ru: '6',
      ruShift: ':',
    },
    {
      code: 'Digit7',
      en: '7',
      enShift: '&',
      ru: '7',
      ruShift: '?',
    },
    {
      code: 'Digit8',
      en: '8',
      enShift: '*',
      ru: '8',
      ruShift: '*',
    },
    {
      code: 'Digit9',
      en: '9',
      enShift: '(',
      ru: '9',
      ruShift: '(',
    },
    {
      code: 'Digit0',
      en: '0',
      enShift: ')',
      ru: '0',
      ruShift: ')',
    },
    {
      code: 'Minus',
      en: '-',
      enShift: '_',
      ru: '-',
      ruShift: '_',
    },
    {
      code: 'Equal',
      en: '=',
      enShift: '+',
      ru: '=',
      ruShift: '+',
    },
    { code: 'Backspace', value: 'Backspace' },
  ],
  [
    { code: 'Tab', value: 'Tab' },
    {
      code: 'KeyQ',
      en: 'q',
      enShift: 'Q',
      enCaps: 'Q',
      ru: 'й',
      ruShift: 'Й',
      ruCaps: 'Й',
    },
    {
      code: 'KeyW',
      en: 'w',
      enShift: 'W',
      enCaps: 'W',
      ru: 'ц',
      ruShift: 'Ц',
      ruCaps: 'Ц',
    },
    {
      code: 'KeyE',
      en: 'e',
      enShift: 'E',
      enCaps: 'E',
      ru: 'у',
      ruShift: 'У',
      ruCaps: 'У',
    },
    {
      code: 'KeyR',
      en: 'r',
      enShift: 'R',
      enCaps: 'R',
      ru: 'к',
      ruShift: 'К',
      ruCaps: 'К',
    },
    {
      code: 'KeyT',
      en: 't',
      enShift: 'T',
      enCaps: 'T',
      ru: 'е',
      ruShift: 'Е',
      ruCaps: 'Е',
    },
    {
      code: 'KeyY',
      en: 'y',
      enShift: 'Y',
      enCaps: 'Y',
      ru: 'н',
      ruShift: 'Н',
      ruCaps: 'Н',
    },
    {
      code: 'KeyU',
      en: 'u',
      enShift: 'U',
      enCaps: 'U',
      ru: 'г',
      ruShift: 'Г',
      ruCaps: 'Г',
    },
    {
      code: 'KeyI',
      en: 'i',
      enShift: 'I',
      enCaps: 'I',
      ru: 'ш',
      ruShift: 'Ш',
      ruCaps: 'Ш',
    },
    {
      code: 'KeyO',
      en: 'o',
      enShift: 'O',
      enCaps: 'O',
      ru: 'щ',
      ruShift: 'Щ',
      ruCaps: 'Щ',
    },
    {
      code: 'KeyP',
      en: 'p',
      enShift: 'P',
      enCaps: 'P',
      ru: 'з',
      ruShift: 'З',
      ruCaps: 'З',
    },
    {
      code: 'BracketLeft',
      en: '[',
      enShift: '{',
      ru: 'х',
      ruShift: 'Х',
      ruCaps: 'X',
    },
    {
      code: 'BracketRight',
      en: ']',
      enShift: '}',
      ru: 'ъ',
      ruShift: 'Ъ',
      ruCaps: 'Ъ',
    },
    {
      code: 'Backslash',
      en: '\\',
      enShift: '|',
      ru: '\\',
      ruShift: '/',
    },
    { code: 'Delete', value: 'Del' },
  ],
  [
    { code: 'CapsLock', value: 'CapsLock' },
    {
      code: 'KeyA',
      en: 'a',
      enShift: 'A',
      enCaps: 'A',
      ru: 'ф',
      ruShift: 'Ф',
      ruCaps: 'Ф',
    },
    {
      code: 'KeyS',
      en: 's',
      enShift: 'S',
      enCaps: 'S',
      ru: 'ы',
      ruShift: 'Ы',
      ruCaps: 'Ы',
    },
    {
      code: 'KeyD',
      en: 'd',
      enShift: 'D',
      enCaps: 'D',
      ru: 'в',
      ruShift: 'В',
      ruCaps: 'В',
    },
    {
      code: 'KeyF',
      en: 'f',
      enShift: 'F',
      enCaps: 'F',
      ru: 'а',
      ruShift: 'А',
      ruCaps: 'А',
    },
    {
      code: 'KeyG',
      en: 'g',
      enShift: 'G',
      enCaps: 'G',
      ru: 'п',
      ruShift: 'П',
      ruCaps: 'П',
    },
    {
      code: 'KeyH',
      en: 'h',
      enShift: 'H',
      enCaps: 'H',
      ru: 'р',
      ruShift: 'Р',
      ruCaps: 'Р',
    },
    {
      code: 'KeyJ',
      en: 'j',
      enShift: 'J',
      enCaps: 'J',
      ru: 'о',
      ruShift: 'О',
      ruCaps: 'О',
    },
    {
      code: 'KeyK',
      en: 'k',
      enShift: 'K',
      enCaps: 'K',
      ru: 'л',
      ruShift: 'Л',
      ruCaps: 'Л',
    },
    {
      code: 'KeyL',
      en: 'l',
      enShift: 'L',
      enCaps: 'L',
      ru: 'д',
      ruShift: 'Д',
      ruCaps: 'Д',
    },
    {
      code: 'Semicolon',
      en: ';',
      enShift: ':',
      ru: 'ж',
      ruShift: 'Ж',
      ruCaps: 'Ж',
    },
    {
      code: 'Quote',
      en: "'",
      enShift: '"',
      ru: 'э',
      ruShift: 'Э',
      ruCaps: 'Э',
    },
    { code: 'Enter', value: 'Enter' },
  ],
  [
    { code: 'ShiftLeft', value: 'Shift' },
    {
      code: 'KeyZ',
      en: 'z',
      enShift: 'Z',
      enCaps: 'Z',
      ru: 'я',
      ruShift: 'Я',
      ruCaps: 'Я',
    },
    {
      code: 'KeyX',
      en: 'x',
      enShift: 'X',
      enCaps: 'X',
      ru: 'ч',
      ruShift: 'Ч',
      ruCaps: 'Ч',
    },
    {
      code: 'KeyC',
      en: 'c',
      enShift: 'C',
      enCaps: 'C',
      ru: 'с',
      ruShift: 'С',
      ruCaps: 'С',
    },
    {
      code: 'KeyV',
      en: 'v',
      enShift: 'V',
      enCaps: 'V',
      ru: 'м',
      ruShift: 'М',
      ruCaps: 'М',
    },
    {
      code: 'KeyB',
      en: 'b',
      enShift: 'B',
      enCaps: 'B',
      ru: 'и',
      ruShift: 'И',
      ruCaps: 'И',
    },
    {
      code: 'KeyN',
      en: 'n',
      enShift: 'N',
      enCaps: 'N',
      ru: 'т',
      ruShift: 'Т',
      ruCaps: 'Т',
    },
    {
      code: 'KeyM',
      en: 'm',
      enShift: 'M',
      enCaps: 'M',
      ru: 'ь',
      ruShift: 'Ь',
      ruCaps: 'Ь',
    },
    {
      code: 'Comma',
      en: ',',
      enShift: '<',
      ru: 'б',
      ruShift: 'Б',
      ruCaps: 'Б',
    },
    {
      code: 'Period',
      en: '.',
      enShift: '>',
      ru: 'ю',
      ruShift: 'Ю',
      ruCaps: 'Ю',
    },
    {
      code: 'Slash',
      en: '/',
      enShift: '?',
      ru: '.',
      ruShift: ',',
    },
    { code: 'ArrowUp', value: '▲' },
    { code: 'ShiftRight', value: 'Shift' },
  ],
  [
    { code: 'ControlLeft', value: 'Ctrl' },
    { code: 'MetaLeft', value: 'Win' },
    { code: 'AltLeft', value: 'Alt' },
    { code: 'Space', value: ' ' },
    { code: 'AltRight', value: 'Alt' },
    { code: 'ArrowLeft', value: '◄' },
    { code: 'ArrowDown', value: '▼' },
    { code: 'ArrowRight', value: '►' },
    { code: 'ControlRight', value: 'Ctrl' },
  ],
];
class Keyboard {
  constructor() {
    this.element = null;
    this.textarea = null;
  }
}
const keyboard = new Keyboard();
document.body.append(keyboard.element);
